= CoolCiv
:experimental:
:source-highlighter: highlight.js
:toc: preamble

This repository contains the web-based CoolCiv project, which implements a HotCiv spin-off from _Flexible, Reliable Software_ by Henrik Bærbak Christensen.

CAUTION: All commands in this README document are to be executed from the project root directory (where this document resides).

== Get Started
This project uses the https://yarnpkg.com/features/zero-installs[zero-install feature] of the Yarn package manager.
Upon cloning the Git repository, the `.yarn/cache` directory already contains a cache of the third-party dependencies, effectively replacing the usual `node_modules` directory.

=== Install Node.js and Yarn
* *macOS* and *Linux* users should install https://nodejs.org/en[Node.js] via https://github.com/nvm-sh/nvm[Node Version Manager] and opt for https://yarnpkg.com/getting-started/install[Yarn] via https://nodejs.org/api/corepack.html[Corepack]:
+
[source,shell]
----
$ curl https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
$ source ~/.bashrc
$ nvm install --lts

$ corepack enable yarn
$ yarn run setup
----

* *Windows* users should install https://nodejs.org/en[Node.js] via https://github.com/microsoft/winget-cli[Windows Package Manager] and install https://yarnpkg.com/getting-started/install[Yarn] via npm (which is actually a workaround until Corepack supports Windows):
+
[source,shell]
----
$ winget install OpenJS.NodeJS.LTS

$ npm install --global yarn
$ yarn run setup
----

=== Prepare Git
. Generate an SSH key, for example using https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent[ssh-keygen] or https://developer.1password.com/docs/ssh/manage-keys[1Password], and add it to the SSH agent on your computer.

* *Windows* users must instruct Git to use https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_overview[Microsoft OpenSSH] as the SSH agent:
+
[source,shell]
----
$ git config --global core.sshCommand "C:/Windows/System32/OpenSSH/ssh.exe"
----

. Register the public key in https://github.com/settings/keys[GitHub] as a signing key.
It appears like `ssh-ed25519 AAAAC3**_<PublicKey>_**`.

. Obtain your masked email address in https://github.com/settings/emails[GitHub].
It appears like `**_<id+username>_**@users.noreply.github.com`.

. Declare your identity within the scope of this repository and use the public key to sign your commits:
+
[source,shell,subs="+quotes,+replacements"]
----
$ git config user.name "**_<FirstName> <LastName>_**"
$ git config user.email "**_<id+username>_**@users.noreply.github.com"

$ git config user.signingkey "ssh-ed25519 AAAAC3**_<PublicKey>_**"
$ git config gpg.format "ssh"
$ git config commit.gpgsign "true"
$ git config tag.gpgsign "true"
----

=== Prepare Your IDE
* *IntelliJ IDEA* (and *WebStorm*) users should open the project directory:
+
[source,shell]
----
$ idea .
----

. Install these plugins (menu:File[Settings > Plugins]):
** https://plugins.jetbrains.com/plugin/7391-asciidoc[AsciiDoc]
** https://plugins.jetbrains.com/plugin/10456-prettier[Prettier]

. Exclude these files from indexing (menu:File[Project Structure > Modules]):
+
[source]
----
.asciidoctor;.yarn;build;coverage;.asciidoctorconfig;.editorconfig;.eslintcache;.eslintignore;.gitattributes;.gitignore;.pnp.cjs;.pnp.loader.mjs;.prettierignore;.yarnrc.yml;yarn.lock
----

. Use Prettier as the formatter for these files: (menu:File[Settings > Languages & Frameworks > JavaScript > Prettier]):
+
[source]
----
{**/*,*}.{cjs,css,html,json,mjs,ts,tsx}
----

. Enable automatic ESLint configuration for these files: (menu:File[Settings > Languages & Frameworks > JavaScript > Code Quality Tools > ESLint]):
+
[source]
----
{**/*,*}.{cjs,mjs,ts,tsx}
----

* *Visual Studio Code* users should open the project directory:
+
[source,shell]
----
$ code .
----

. Install these extensions (kbd:[Ctrl+Shift+X]):
+
** https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode[AsciiDoc]
** https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint[ESLint]
** https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode[Prettier]

== Tasks
The `scripts` field in `package.json` defines a set of work tasks.
Corresponding IntelliJ IDEA configurations are located in `.idea/runConfigurations`.

=== Start a Local Development Server
[source,shell]
----
$ yarn run develop
----

Visit http://localhost:8000 to access the web app from your local computer.
Use the LAN IP address printed in the console (usually something like `192.168.X.Y`) to access it from another device.

=== Validate the Software Quality
[source,shell]
----
$ yarn run validate
----

It runs the following means of validation:

* *Type checking* via https://www.typescriptlang.org[TypeScript] (`validate:types`).
* *Source code formatting* via https://prettier.io[Prettier] (`validate:format`).
** `validate:format:fix` formats the source code files accordingly.
* *Static program analysis* (linting) via https://eslint.org[ESLint] (`validate:lint`).
** `validate:lint:fix` fixes certain issues automatically.
* *Automated unit testing* via https://vitest.dev[Vitest] (`validate:test`).
** `validate:test:coverage` creates a code coverage report in the `coverage` directory.
** `validate:test:ui` launches the https://vitest.dev/guide/ui.html[Vitest user interface] in a web browser.
** `validate:test:watch` makes the test suite run continuously.

=== Build for Production
[source,shell]
----
$ yarn run build
----

It saves the output in the `build` directory.

* `build:preview` serves a preview at http://localhost:80.
