name: Verify pull requests
on: [ pull_request ]
jobs:
    validate-software-quality:
        name: Validate the software quality
        runs-on: ubuntu-latest
        steps:
            -   name: Check out the repository
                uses: actions/checkout@v3
            -   name: Prepare Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: 18
                    cache: yarn
            -   name: Install dependencies
                run: yarn install --immutable
            -   name: Check types
                run: yarn run validate.types
            -   name: Verify the source code format
                run: yarn run validate.format
            -   name: Lint
                run: yarn run validate.lint
            -   name: Run the unit tests
                run: yarn run validate.test
#    verify-commit-messages:
#        name: Verify the commit messages
#        runs-on: ubuntu-latest
#        steps:
#            -   name: Check out the repository
#                uses: actions/checkout@v3
#            -   name: Prepare Node.js
#                uses: actions/setup-node@v3
#                with:
#                    node-version: 18
#                    cache: yarn
#            -   name: Install dependencies
#                run: yarn install --immutable
#            - name: Verify the commit messages
#              run: node .github/scripts/verify-commit-messages-of-pull-request.js
#              env:
#                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
